version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@database:5432/hakaton'
    networks:
      - backend
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hakaton
    ports:
      - '5432:5432'
    networks:
      - backend
networks:
  backend:
