export { GetOneEndpoint } from './get-one-endpoint.decorator'
export { GetAllEndpoint } from './get-all-endpoint.decorator'
export { AutocompleteEndpoint } from './autocomplete-endpoint.decorator'
export { CreateEndpoint } from './create-endpoint.decorator'
export { UpdateEndpoint } from './update-endpoint.decorator'
export { UpdatePartiallyEndpoint } from './update-partially-endpoint.decorator'
export { DeleteEndpoint } from './delete-endpoint.decorator'
